ovh/venom

README.md
assertion.go
cli/venom/run/cmd.go
executors/smtp/README.md
executors/smtp/executor.go
templater.go
tests/MyTestSuiteSMTP.yml
vendor/github.com/smartystreets/assertions/equality.go

feat(executorSMTP)

---

README.md
executors/exec/README.md
executors/exec/executor.go
tests/MyTestSuiteExec.yml

And lowercase for att json / yaml to avoid confusion

doc (executorExec): multiline

---

README.md
assertion.go
cli/venom/run/cmd.go
executors/exec/executor.go
process.go
types.go

fix: inconsistent xml output

---

process.go

fix: call runTestStepExecutor

---

README.md
executors/exec/README.md

fix: doc exec

---

process.go
process_bars.go
process_files.go
process_testcase.go
process_teststep.go
process_testsuite.go
tests/MyTestSuiteWeb.yml
venom.go

fix: alphabetical order

---

README.md
assertion.go
extract.go
process_teststep.go
tests/MyTestSuiteExec.yml
types.go

feat(venom): extract named variables from result

---

vendor/github.com/fsamin/go-dump/dump.go
vendor/vendor.json

chore: update go-dump

---

README.md

doc: yml format

---

cli/venom/run/cmd.go
process.go
process_testsuite.go
venom.go

refactor: move output to sdk

---

executors/http/README.md
executors/http/executor.go

Venom will first try to load config from body if specified, then from bodyFile if specified.

Use file for request body

---

cli/venom/run/cmd.go
process.go
process_files.go

feat (venom, cli): allow using another io.writer

---

cli/venom/run/cmd.go
context/default/context.go
executors/ovhapi/README.md
executors/ovhapi/executor.go
process_testcase.go
templater.go

Signed-off-by: Ludovic Lamarche <ludovic.lamarche@corp.ovh.com>

add test executor for ovh api

---

context/webctx/context.go
executors/web/README.md
executors/web/web.go

feat (webCtx): timeout on ctx

---

vendor/github.com/ovh/go-ovh/LICENSE
vendor/github.com/ovh/go-ovh/ovh/configuration.go
vendor/github.com/ovh/go-ovh/ovh/consumer_key.go
vendor/github.com/ovh/go-ovh/ovh/error.go
vendor/github.com/ovh/go-ovh/ovh/ovh.go
vendor/gopkg.in/ini.v1/LICENSE
vendor/gopkg.in/ini.v1/Makefile
vendor/gopkg.in/ini.v1/README.md
vendor/gopkg.in/ini.v1/README_ZH.md
vendor/gopkg.in/ini.v1/error.go
vendor/gopkg.in/ini.v1/ini.go
vendor/gopkg.in/ini.v1/key.go
vendor/gopkg.in/ini.v1/parser.go
vendor/gopkg.in/ini.v1/section.go
vendor/gopkg.in/ini.v1/struct.go
vendor/vendor.json
venom.go

chore: vendor

---

executors/imap/README.md
executors/imap/executor.go

feat (executor/imap): search body

---

README.md
cli/venom/run/cmd.go

doc: tap format

---

.travis.yml
README.md
cli/venom/main.go
cli/venom/run/cmd.go
cli/venom/template/cmd.go
cli/venom/update/cmd.go
cli/venom/version/version.go
context/default/context.go
context/webctx/context.go
executors/exec/executor.go
executors/http/executor.go
executors/imap/decode.go
executors/imap/executor.go
executors/ovhapi/executor.go
executors/readfile/executor.go
executors/smtp/executor.go
executors/ssh/executor.go
executors/web/README.md
executors/web/web.go
lib/lib.go
libtests/libtests_test.go
package.sh
vendor/vendor.json

chore: move from runabove to ovh

---

templater.go

Now you can have even more flexibility with your testsuite variables.
```yaml
name: My TestSuite
vars:
api.port: 8086
api.url: http://localhost:{{.api.port}}
```
_gonna add tests_

feat (template): template templater's values with themselves.

---

executors/imap/executor.go

FYI: https://github.com/mxk/go-imap/issues/18
Code is borrowed from this issue.

feat(executor/imap): add deleteonsuccess option to delete a mail once found.

---

venom.go

@yesnault @fsamin @sguiheux Should I add an option to disable pretty printing ?
fix https://github.com/ovh/venom/issues/94

feat(venom): pretty print XML and JSON output of testsuite results.

---

venom_output.go

fix: remove explicit newline

---

types.go

refactor: remove unused Assertions on TestCase

---

executors/ovhapi/executor.go

Signed-off-by: Marc Audefroy <marc.audefroy@corp.ovh.com>

fix: duplicate headers. Use Set instead of Add

---

README.md

README flags were a little out-of-date compared to actual flags.

Update venom run flags in README

---

package.sh

chore: cgo

---

package.sh
process_files.go
process_testcase.go
process_teststep.go
templater.go
tests/TestVars.yml
venom_output.go

and add all variables in dump files if there is a failure

fix(venom): re-templating vars

---

executors/exec/executor.go
process.go
process_testsuite.go
templater.go
tests/MyTestSuiteWithVenomBuiltinVar.yml

fix: apply templater on vars

---

process_testcase.go

fix(venom): add vars to extracted vars check func

---

process.go
process_testcase.go

fix(venom): take extracted ts.vars only once

---

cli/venom/run/cmd.go
executors/kafka/README.md
executors/kafka/executor.go
tests/MyTestSuiteKafka.yml

Hi,
Here a first draft to implements a kafka executor. 
Thanks for your review and advise.

[Ready] A first draft to implements a kafka executor

---

CONTRIBUTING.md
README.md
executors/http/README.md
executors/imap/README.md
executors/kafka/README.md
executors/ovhapi/README.md
executors/redis/README.md
executors/smtp/README.md
executors/ssh/README.md
executors/web/README.md

This PR fixes some typos, misspellings and punctuations.
Happy Hacktoberfest 🎃

doc: fix typos and misspellings

---

process.go

Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

fix: fail if errors hapened

---

process_teststep.go
tests/MyTestSuiteHTTP.yml

fix: store failure on last retry only

---

executors/ssh/executor.go

fix(executor/ssh): fix HostKeyCallback

---

Gopkg.toml
README.md
cli/venom/run/cmd.go
executors/grpc/README.md
executors/grpc/executor.go
lib/lib.go
tests/MyTestSuiteGrpc.yml

Add GRPC executor which uses grpcurl to do requests to grpc endpoints.
Fixes: https://github.com/ovh/venom/issues/187
Signed-off-by: Matous Dzivjak <matous.dzivjak@kiwi.com>

feat(executor/grpc): Add GRPC executor (ovh#187)

---

executors/dbfixtures/README.md
executors/dbfixtures/executor.go

Add migrationsTable field in dbfixture to choose table used to store migration version

feat(migration): Add migrationsTable in dbfixture

---

README.md
cli/venom/run/cmd.go
executors/sql/README.md
executors/sql/executor.go
lib/lib.go

feat(executors): add sql executor to query databases

---

executors/http/executor.go

Closes #217 
Signed-off-by: Tit Petric <tit.petric@monotek.net>

fix(executor/http): support setting host in headers

---

context/webctx/context.go
executors/web/README.md
executors/web/types.go
executors/web/web.go

Hello, 
Implement agouti next window on venom
Take care, there are a dependency with "Add gecko web driver" pull request.
Regards

Feature - GUI - Implement next window

---

executors/http/executor.go

I've added support for reading proxy configuration from environment variables.

feat(http): read proxy from environment

---

.gitignore
README.md
cli/venom/run/cmd.go

feat(cli): allow multiple occurence of --var-from-file

---

cli/venom/run/cmd.go

fix(cli): give higher priority to --var over --var-from-file

---

cli/venom/run/cmd.go

doc: some doc on venom run cmd

---

tests/MyTestSuiteHTTP.yml

test: fix some http asserts

---

process_testsuite.go

fix: do not truncate filename in results

---

tests/MyTestSuiteKafka.yml

test(executor/kafka): it

---

cli/venom/update/cmd.go

fix(cli): do not re-download if not needed

---

process_files.go
process_files_test.go

fix(venom): error on no yml file

---

cli/venom/run/cmd.go
process.go
venom.go

this feature can be done with parallel
ls *.yml|parallel -j 2 venom run {}

refacto(venom): delete --parallel flag

---

README.md
cli/venom/run/cmd.go

refactor: remove flag --strict, exit 2 if err

---

tests/assertions.yml
tests/redis.yml
tests/web.yml

fix: integration tests

---

README.md

doc: docker run

---

LICENSE
README.md

Apache License, Version 2.0

---

.build/go.mk
Makefile
README.md
cmd/venom/run/cmd_test.go
executors/plugins/Makefile
executors/plugins/README.md
executors/plugins/hello/Makefile
executors/plugins/hello/hello.go
executors/plugins/odbc/Makefile
executors/plugins/odbc/README.md
executors/plugins/odbc/odbc.go
executors/sql/README.md
executors/sql/sql.go
go.mod
go.sum
tests/Makefile
venom.go

feat: plugins support

---

executors/http/README.md
executors/http/http.go
process_teststep.go
tests/http.yml

feat: add request in HTTP executor result

---

executors/redis/README.md
executors/redis/redis.go
tests/redis.yml

fix: redis executor dialURL and documentation

---

README.md
executors/exec/README.md
executors/exec/exec.go
executors/grpc/README.md
executors/grpc/grpc.go
executors/http/README.md
executors/http/http.go
executors/imap/imap.go
executors/kafka/kafka.go
executors/ovhapi/README.md
executors/ovhapi/ovhapi.go
executors/rabbitmq/rabbitmq.go
executors/readfile/README.md
executors/readfile/readfile.go
executors/smtp/smtp.go
executors/ssh/README.md
executors/ssh/ssh.go
executors/web/README.md
executors/web/web.go

fix: executors documentation and remove timeHuman everywhere

---

go.mod
go.sum

fix: update go-dump dep

---

executors/http/http.go
executors/readfile/readfile.go

Signed-off-by: Kevin RAMAGE <kevinramage@hotmail.fr>

feat(executor/http): decode json with big number

---

cmd/venom/run/cmd.go
process.go
process_teststep.go
process_testsuite.go
types.go
venom.go

feat: improve -vv results

---

README.md
venom_output.go

feat: handler IS_TTY env variable to display color

---

executors/kafka/kafka.go

fix(executor/kafka): timeout in seconds

---

.gitignore
README.md
cmd/venom/run/cmd.go
go.mod
go.sum
process.go

feat: read venom flags from configuration file

---

process.go

fix: dont read two times the testsuites

---

README.md
assertion.go
process_testcase.go
process_testsuite.go
tests/skip.yml
types.go

feat: skip testcase

---

README.md

doc: assertions list

---

README.md

doc: add missing builtin variables

---

LICENSE
README.md

doc: copyright

---

executors/dbfixtures/dbfixtures.go
executors/exec/exec.go
executors/grpc/grpc.go
executors/http/http.go
executors/imap/imap.go
executors/kafka/kafka.go
executors/ovhapi/ovhapi.go
executors/plugins/README.md
executors/plugins/hello/hello.go
executors/plugins/odbc/odbc.go
executors/rabbitmq/rabbitmq.go
executors/readfile/readfile.go
executors/redis/redis.go
executors/smtp/smtp.go
executors/sql/sql.go
executors/ssh/ssh.go
executors/web/web.go
process_testcase.go
tests/user_executor.yml
types_executor.go

fix: parse missing vars

---

assertions/assertions.go
assertions/assertions_test.go
tests/readfile.yml
tests/readfile/testa.json

fix: shouldEqual with int value

---

executors/http/README.md
executors/http/http.go
executors/http/httputil.go
go.mod

feat(executor/http): Mutual TLS

---

.build/core.mk
.build/go.mk
cmd/venom/Makefile

fix: version flag

---

cmd/venom/run/cmd.go
cmd/venom/run/cmd_test.go

fix(venom): parsing --vars

---

README.md

doc: copyright 2021

---

tests/lib/foobar.yml
tests/user_executor.yml
venom.go

fix(venom): multiple user executors

---

README.md
assertion.go
assertions/assertions.go
assertions/assertions_test.go
go.sum
process_testcase.go
process_teststep.go
tests/lib/hello.yml
tests/play-with-vars.yml
tests/user_executor.yml
types.go
types_executor.go

and fix display line number for info

fix(venom): use vars as string or struct

---

executors/http/README.md
executors/http/http.go
tests/http_resolve_test.yml

feat(executor/http): resolve attribute

---

README.md
assertion.go
assertions/assertions.go
cmd/venom/run/cmd.go
dump.go
executors/http/http.go
process.go
process_files.go
process_testcase.go
process_teststep.go
process_testsuite.go
read_partial.go
read_partial_test.go
tests/Makefile
tests/lib/hello.yml
tests/lib/withArray.yml
tests/play-with-vars.yml
tests/user_executor.yml
tests/user_executor_with_array.yml
tests/vars_quoted.yml
types_executor.go
venom.go

fix(venom): parse complex vars 

---

cmd/venom/run/cmd.go

fix(venom): .venomrc parsing

---

process_teststep.go
types_executor.go

fix: display failures on user executor

---

README.md
cmd/venom/run/cmd.go
tests/Makefile
tests/lib_custom/foobar_custom.yml
tests/user_executor_custom.yml
venom.go

feat: add optionnal flag --lib-dir

---

process_files.go
tests/random_vars.yml

fix: ts vars interpolation only once

---

README.md
venom.go

doc: faq about json and quotes

---

executors/grpc/grpc.go

👋  Hey OVH
I'm facing a panic issue while trying to use the gRPC executor:
``` 
Title of TestSuite (venom.yml)
• request-GRPCpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16d7510]
goroutine 1 [running]:
github.com/ovh/venom/executors/grpc.Executor.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/ovh/venom/executors/grpc/grpc.go:146 +0x1020
github.com/ovh/venom.(*Venom).runTestStepExecutor(0xc0002faa20, 0x1e8ca40, 0xc00032c480, 0x1e9c1e0, 0xc0000b6fc0, 0xc00012cc00, 0xc00023bec0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/ovh/venom/process_teststep.go:130 +0x18a
github.com/ovh/venom.(*Venom).RunTestStep(0xc0002faa20, 0x1e8ca40, 0xc00032c3f0, 0x1e9c1e0, 0xc0000b6fc0, …
```

Return error to avoid panic

---

cmd/venom/run/cmd.go

fix: verbose flag if nil

---

.build/go.mk
cmd/venom/main_test.go
go.mod
go.sum
tests/.gitignore
tests/Makefile
tests/venom_wrapper.sh

Signed-off-by: richardlt <richard.le.terrier@gmail.com>

chore: compute coverage

---

README.md
cmd/venom/run/cmd.go
executors/mqtt/README.md
executors/mqtt/mqtt.go
go.mod
go.sum
tests/Makefile
tests/mqtt.yml
tests/mqtt/mosquitto.conf

Add new executor to support MQTT message brokers
Signed-off-by: Simon Truss <Simon.Truss@90poe.io>

initial implementation of mqtt executor

---

README.md

doc(readme): amqp and globstar

---

executors/README.md

Found some errors in executor example while exploring

Fix example executor code

---

cmd/venom/run/cmd.go

fix: format arg default value

---

assertions/assertions.go
tests/assertions/ShouldContain.yml

fix: assertion ShouldContain can handle single value

---

process.go
types.go

fix: compute stats ok/ok/skipped on json format

---

.gitignore
go.mod
go.sum
tests/interpolation.yml

fix: interpolation lib bad µµµ replacement

---

Makefile
cmd/venom/Makefile
cmd/venom/run/cmd.go
tests/Makefile

chore: make clean + golang 1.17 for integration tests

---

.gitignore
cmd/venom/main.go
cmd/venom/run/cmd.go
git-template

The goal of this PR is to try to improve User eXperience and Developer eXperience in the CLI of Venom with usage/help messages improvements.

Improve UX & DX in Venom CLI

---

README.md

doc: testsuite sort on venom run

---

README.md

Following the [PR 491](https://github.com/ovh/venom/pull/491), it can be useful to update the README with updated usage messages.

doc: update readme with new usage messages

---

go.mod
go.sum

chore: bump interpolate lib

---

executors/ssh/README.md
executors/ssh/ssh.go
executors/ssh/sshutil.go
tests/Makefile
tests/ssh.yml

This PR add new field sudo to SSH executor.
You can set the user you want to become.

feat(ssh_executor): Sudo option

---

.build/go.mk

chore: Makefile - fix cross compilation

---

executors/readfile/README.md

docs(contrib): review of readfile/README.md

---

executors/web/README.md

docs(contrib): typo and review of web/README.md

---

executors/web/web.go

docs(contrib): typo and review of web/web.go

---

executors/README.md

docs(contrib): typo and review of executors/README.md

---

executors/exec/README.md

docs(contrib): typo and review of exec/README.md

---

assertions/assertions.go
executors/http/http.go
go.mod
go.sum
process.go
process_files.go
process_testcase.go
tests/Makefile
tests/http.yml
tests/lib_custom/foobar_http.yml
tests/lib_custom/foobar_http_get.yml
tests/lib_custom/foobar_http_get_user.yml
tests/user_executor_http_direct.yml
tests/venom_wrapper.sh
venom.go

fix: step variables inheritance leak

---

.build/go.mk

chore: use go install

---

.gitpod.yml
README.md

chore: enable git pod

---

process.go

fix: disable colors in venom.log file

---

README.md
tests/lib/multilines.yml
tests/multilines.yml
venom.go

fix: multilines in args user executor

---

Dockerfile
README.md

feat: official docker image

---

README.md
variable_helpers.md

doc: variables helpers examples

---

executors/http/README.md
executors/http/http.go

fix(executor/http): preserveBodyFile interpolation

---

executors/kafka/kafka.go

This PR includes two fixes over Kafka consumer executor:
1. waitFor didn't work in some cases mixed with timeout property
as it is reused by test executor. Using a goroutine over
consume claim we can work on timeout and wait for without issues.
2. messageLimit after #448 may only work if there are more messages to
consume in the topic, if the message limit is hit after consuming the
last message from the topic, the condition is never met and it waits
until timeout is reached leading to longer Kafka consumer step
executions.

Fix waitFor and messagesLimit behaviour in Kafka consumer

---

process_testcase.go
process_teststep.go
types.go

- Added number of retries made when a teststep is in success: closes #602 
- Show the last list of errors when a teststep is in error

feat: show latest assertions errors in case of retry + added number of retries when success

---

executors/readfile/README.md
executors/readfile/readfile.go
tests/readfile.yml
tests/readfile/test.yml

Have the ability to parse yaml files as well and give the contentjson

parse yaml files in the readfile

---

executors/kafka/README.md
executors/kafka/kafka.go
tests/kafka.yml

Support Kafka Headers as mentioned in https://github.com/ovh/venom/issues/690

add kafka headers for producer

---

README.md
cmd/venom/run/cmd.go
process_testcase.go
process_teststep.go

and documentation on how to use secrets feature

fix: secrets in dump.json and venom.log files

---

process_testcase.go

fix(venom): panic on failure

---

executors/ovhapi/README.md
executors/ovhapi/ovhapi.go
go.mod
go.sum

Update `ovhapi` executor to add ability to use OAuth2 authentication.

feat(ovhapi): add support for OAuth2 authentication
