ovh/venom

README.md, assertion.go, process.go, tests/MyTestSuiteHTTP.yml, types.go, venom.go
=> feat: add retry / delay on teststep

executors/http/executor.go
Hi,
the executor is not forwarding JSON body, now it will.
Signed-off-by: Geoffrey Bauduin <bauduin.geo@gmail.com>
=> fix: http executor should forward body

README.md, process.go, types.go, venom.go
with a fix on https://github.com/runabove/venom/compare/timeoutStep?expand=1#diff-9db914ba50bc6d534b92b9539cc7b3a1R59
=> feat: timeout on step

templater.go
this avoid this error on cds
```
2017/02/20 12:00:21 [DEBUG] plugin: template-3: 2017/02/20 12:00:21 rpc: gob error encoding body: gob: type venom.Templater has no exported fields
```
(and could be usefull in venom SDK too)
=> feat: expose Values of Templater

README.md, executors/http/executor.go, templater.go, tests/MyTestSuiteHTTP.yml
I need this feature, but I find my method too "hacky" because of encode/decode and behaviors of the used encoding libraries.
**First issue I came up with, in templater:** 
```
templater> Error while marshaling: json: unsupported type: map[interface {}]interface {}
templater> Error while marshaling: json: unsupported type: map[interface {}]interface {}
templater> Error while marshaling: json: unsupported type: map[interface {}]interface {}
```
It appears `json` does not really like `map[interface{}]interface{}` type (and does not know what to do with it), while `yaml` (it's the one producing this type) is okay with it (hence the modification in `templater.go`)
**Second issue I came up with, in the executor**
Basically, `mapstructure.Decode` does not know how to handle the `MultipartForm` …
=> feature: HTTP executor can POST multipart

README.md, assertion.go, executors/exec/executor.go, executors/http/executor.go, executors/imap/decode.go, executors/imap/executor.go, executors/readfile/executor.go, executors/smtp/executor.go, executors/ssh/executor.go, executors/web/web.go, extract.go, lib/lib.go, lib/libtests.go, libtests/libtests_test.go, process_testcase.go, process_teststep.go, process_testsuite.go, templater.go, types.go, venom.go
Sample usage
```golang
func TestVenomTestCase(t *testing.T) {
v := venom.TestCase(t, "TestVenomTestCase", venom.V{
"foo": "bar",
})
r := v.Do(venom.H{
"type":   "exec",
"script": "echo {{.foo}}",
})
assert.Equal(t, "bar", r["result.systemout"])
}
```
still have to improve it; with some docs also
=> feat: venom as Lib

assertion.go, executors/exec/executor.go, extract.go, extract_test.go, process_testcase.go, process_teststep.go
otherwise, unmarshal json of TestSuite will fail with:
"invalid character '\x1b' in string literal"
Play on https://play.golang.org/p/8Ds1S9AJnN
=> fix: remove noPrintable char from Failure & Output

assertion.go, assertion_test.go
live example: https://play.golang.org/p/7X9XRj-I0I
=> feat (assertion): support quoted args when splitting assertion string.

process_files.go, process_testsuite.go, types.go, venom.go
Skipped is a block, not an attribute
=> fix (venom): tc skipped format

cli/venom/run/cmd.go
Strict mode allows to exit with an error code (`2`) if one test fails.
=> feat (venom): add strict run mode

.travis.yml, README.md, assertion.go, cli/cli.go, cli/venom/run/cmd.go, cli/venom/template/cmd.go, cli/venom/update/cmd.go, executors/dbfixtures/executor.go, executors/exec/executor.go, executors/http/executor.go, executors/imap/executor.go, executors/ovhapi/executor.go, executors/readfile/executor.go, executors/smtp/executor.go, executors/ssh/executor.go, executors/web/web.go, extract.go, lib/lib.go, lib/libtests_test.go, process.go, process_bars.go, process_files.go, process_testcase.go, process_teststep.go, process_testsuite.go, tests/MyTestSuiteWithExtract.yml, types.go, venom.go, venom_output.go
It includes a bit of refacto.
On venom.Process it parse all testsuites to find :
* variables usages
* all extracted variables (including default extractible variables in the executor result structure).
If a variable is used but it not extracted, not extractible and not set as `--var`. An error is raised
example: 
````
➜  tests git:(master) ✗ pwd
$GOPATH/src/github.com/ovh/venom/tests
➜  tests git:(master) ✗ venom run *.yml
FATA[0001] Missing variables [mysqlhost postgreshost]
➜  tests git:(master) ✗ venom run *.yml --var mysqlhost=localhost:5555
FATA[0001] Missing variables [postgreshost]
````
=> feat: parse all testsuites to check variables usage

executors/http/README.md, executors/http/executor.go, process_testcase.go, process_teststep.go, tests/MyTestSuiteHTTP.yml
to be able avoid big memory footprint in the testcase
=> feat (executor/http): option to skip body and headers

cli/venom/template/cmd.go
Without this fix, the sample template produced by `venom template` creates an error and creates a bad taste in someone's mouth who is new to `venom`.
=> Update the output from `venom template` to match reality.

README.md, executors/exec/executor.go, executors/http/executor.go, executors/imap/executor.go, executors/ovhapi/executor.go, executors/readfile/executor.go, executors/smtp/executor.go, executors/ssh/executor.go, executors/web/web.go, lib/lib.go, process_files.go, types.go, venom_output.go
This is a trivial PR centered around the use of `go-rename` at various places.
Clean up various variable names, notably freeing `t` from overloaded use.
`t`'s overloaded use included:
* `testing.T`
* `TestSuite`
* `Executor`
* `tap.Tap`
Give each their own distinct meaning, leaving `t` for `testing.T` as
this is the idiomatic way `t` is used.  Renames performed using `go-rename(1)`.
There is also a tiny amount of whitespace and alpha-sorting that felt like small repo churn and was included in this PR as separate commits.  The aim of this PR is to improve code readability.
=> Executor variable name

executors/http/README.md
This bugged me for a while, so it's probably worth it adding it to the
README file.
=> Document bodyjson keys being lowercase

executors/exec/executor.go
This should solve issue #140.
When a script outputs something with no '\n' at the end, the executor
did not capture the output. Golang `ReadString` documentation specifies
that it's safe to use the read string even if an error occured (that's
rather unusual in Go...):
```
ReadString reads until the first occurrence of delim in the input,
returning a string containing the data up to and including the
delimiter. If ReadString encounters an error before finding a
delimiter, it returns the data read before the error and the error
itself (often io.EOF). ReadString returns err != nil if and only if
the returned data does not end in delim. For simple uses, a Scanner
may be more convenient.
```
=> Capture exec outputs with no line break

README.md, cli/venom/run/cmd.go, process_testsuite.go, venom.go
This allows running tests as usual, but will stop a TestSuite at the
first TestCase failure.
This makes sense in case there are dependencies between TestCases, eg.
the first TestCase creates a resource on a REST API, and following
TestCases are doing some stuff with this resource.
I tested it locally (with and without the new flag), but did not find a
proper place in the repository to add unit tests for that feature.
=> Add a flag to stop running TestSuite on TestCase failure

executors/dbfixtures/executor.go
The `DBFixtures` executor can use an array of paths to schema files, or can use the path to a folder containing all migrations to apply. In his PR https://github.com/ovh/venom/pull/145, @marcaudefroy forgot to join the workdir of the migration folder path, which lead to issues with testsuites in version 2 using relative paths.
=> fix: join workdir path with migration folder too in DBFixtures executor.

executors/imap/decode.go, executors/imap/executor.go
If one of the `Subject`, `From`, `To` headers cannot be decode properly, we should return an error and leave the choice to the calling function to decide what to do about it. The `extract` has no knowledge about the search filters that will be used to filter the mails anyway.
=> executors/imap: return an error when one of the Headers cannot be decoded

executors/http/README.md, executors/http/executor.go
This P.R adds a new parameter to the `http` executor that allows to use the _Unix sockets_ transport layer.
Example:
```yaml
- name: GET API health over Unix Socket
steps:
- type: http
method: GET
unix_sock: /run/myapp/health.sock
url: http://unix/health
assertions:
- result.bodyjson.success ShouldBeTrue
```
=> Add support for talking HTTP over Unix socket

executors/imap/README.md, executors/imap/decode.go, executors/imap/executor.go
and ignore error on content-type, it's possible to not be able to decode this field, even with a real imap srv
the default assertion move to ShouldNotBeEmpty, the key err was already here (we don't see this behaviour with a real assertion)
Signed-off-by: Yvonnick Esnault <yvonnick@esnau.lt>
=> fix(executor/imap): add flag InsecureSkipVerify

executors/grpc/README.md, executors/grpc/executor.go
Fix documentation for gRPC executor missing some available
configuration and also accidentally copied text from README of other
executor.
Fix decoding names of configuration fields.
=> executor/grpc: Fix documentation and configuration

cli/venom/run/cmd.go
With current behaviour `for _, f := range varFiles {}` loop will try to open a file named `""` is no file names are given with `--var-from-file=`. 
This should skip it.
=> Fix (cli): don't iterate over empty varFiles

context/webctx/context.go, executors/web/README.md
=> feat(context/web): add prefs for chromedriver (#257)

executors/http/executor.go
When developing tests with the http executor, we're sometimes "blind" with the response content (especially when dealing with BodyJSON). Can be tricky to debug. Found useful to display some infos (response body and status) *only* when venom is launched with --log debug
Signed-off-by: Francois Lesage <francois.lesage@gmail.com>
=> feat(executor/http): added http debug infos in http executor

executors/http/executor.go
In case the server returns multiple set-cookie headers, only the first returned set-cookie is being saved in the response headers. The others set-cookies are discarded. This can make tests fail, in case we need to reuse a previous returned set-cookie as a new cookie on a following test.
=> Save multiple set-cookie headers when returned by the server

README.md
I've just added tiny information about how to get venom-cli with `go get`.
=> Add go-get info for cli to README

CONTRIBUTING.md
The link https://www.kernel.org/doc/Documentation/SubmittingPatches has been moved to https://www.kernel.org/doc/Documentation/process/submitting-patches.rst
=> Update link to Submitting-Patches on CONTRIBUTING.md

process_files.go
Users have to filter the yml files given to venom if needed
close #234
close #235
=> fix: don't ignore invalid yml files

executors/web/web.go
In some case, it's complexe to understand why some web test failed, especially with phantomjs which not use the last version of javascript. This PR save the HTML of the  current page in a file if an error occurred during the element selection.
=> Add system to save the html when an error occurred during the element selection

README.md, executors/http/executor.go, executors/ovhapi/executor.go, executors/rabbitmq/executor.go
executors rabbit/ovhapi fixed too
close #249
=> fix(executor/http): default assertion

README.md, go.mod, go.sum
=> doc: prerequisite make build

README.md, executors/sql/README.md, executors/sql/sql.go, go.mod, go.sum
until executor as plugin is available, this will let everybody compile
and run venom without installing unixodbc library.
=> fix(executor/sql): removing odbc for now

README.md, cli/venom/run/cmd.go, executors/imap/imap.go, process.go, process_teststep.go, process_testsuite.go, venom.go, venom_output.go
only one flag now:
venom run -v foo.yml: debug mode
venom run -vv foo.yml: debug mode with CPU Profiling
=> feat: replace enableProfiling and log-level flags

README.md, cli/venom/run/cmd.go
variables have to be listed on the top of the testsuite
=> refactor: remove -no-check-variables argument

README.md, cmd/venom/run/cmd.go, process.go, process_teststep.go
=> feat: argument as environment variables

executors/readfile/README.md, executors/readfile/readfile.go, process_testcase.go, tests/readfile.yml
and fix default assertion on readfile executor
=> fix: reuse vars from testcase

cmd/venom/.gitignore, cmd/venom/run/cmd.go, cmd/venom/run/cmd_test.go, log.go, process.go, process_files_test.go, process_testcase_test.go, tests/Makefile, tests/vars.yml, tests/vars/vars.yml
```
❯ cat vars.yml
---
timezone: "{{.TIMEZONE}}"
❯ cat env_vars.yml
name: Environment variables
version: 2
testcases:
- name: echo_timezone
steps:
- type: exec
script: "echo {{.timezone}}"
info: "{{.timezone}}"
❯ VENOM_VAR_TIMEZONE=UTC ./venom run env_vars.yml --var-from-file vars.yml -vv
[trac] writing venom.log
• Environment variables (env_vars.yml)
• echo_timezone SUCCESS
[info] UTC (env_vars.yml:0)
[trac] writing Environment-variables.echo_timezone.step.0.dump.json
```
close #350
=> fix: take care of venom variables on parse file

process_testcase.go
slug on tc.name is already applied on parseTestCases func. This func is now always called before v.Process
close #358
=> fix(venom): display line number on failure / info

dump.go, process_testcase.go, process_teststep.go, process_testsuite.go, read_partial.go, tests/lib/user_executor_A.yml, tests/lib/user_executor_B.yml, tests/user_executor_many.yml, types.go, types_executor.go, venom.go
close #371
fix display info from user executor
=> fix: user_executor inside user_executor

go.mod, go.sum
Goavro  v2.9.8 contains a bug for parsing timestamp (PR here: https://github.com/linkedin/goavro/pull/213)
This bug has been fixed in v2.10.0
This PR is about upgrade Goavro to the last version.
Reviews and feedback are welcome :)
=> Update goavro dependency

executors/grpc/README.md
It seems the readme does not match the codebase.
Here is a fix proposal
=> Fix readme for gRPC executor

executors/kafka/README.md, executors/kafka/kafka.go, tests/kafka.yml
Firstly, thanks for this amazing project.
This allows test to consume as an unknown number of messages during a period time. This is a way to solve the issue when you don't know the number of messages the test suite will have to consume, eg when running same test suite against the same topic more than once. This is specially useful when consuming topics from the `oldest` offset.
`Timeout` is left untouched to mark test as failed when a maximum number of messages are expected and timeout is reached. This way this change is backwards compatible.
Example of usage of `waitFor` attribute:
```yaml
- type: kafka
clientType: consumer
initialOffset: "oldest"
groupID: "{{ randAlpha 6 }}"
markOffset: false
waitFor: 5  # This consumes messages for 5 seconds
addrs:
- "localhost:9092"
topics:
- …
```
=> Add wait_for attribute to consume messages for X seconds in kafka consumer executor

executors/kafka/README.md, executors/kafka/kafka.go
This way the number of results to do assertions on are much lower and ease the reproducibility and reliability of test suites.
This is an improvement over using `jq` as `exec` executor in the next step / test.
Here `string` is expected to use as key_filter because `Message` struct uses string as `Key` attribute.
Example of usage:
```yaml
- type: kafka
clientType: consumer
initialOffset: "oldest"
groupID: "{{ randAlpha 6 }}"
keyFilter: "my_key"
addrs:
- "localhost:9092"
topics:
- "my_topic"
```
Any review or feedback is more than welcome :hugs:
=> Add key_filter attribute to kafka consumer executor

executors/kafka/kafka.go
:wave: again !
This is based on #394 to avoid conflicts so it may be better to read two last commmits.
Two minor improvements:
1. Introduce a mutex to share access to `messages` and `messagesJSON` between goroutines when more than 1 partition per topic is added.
2. Use `sarama.ConsumerGroupSession` context in `ConsumeClaim` for logging avoiding creating a new context when the parent one is already available.
Any review or feedback is more than welcome :hugs:
=> Improvements over kafka consumer executor

assertion.go, tests/assertions.yml
👋🏻  2 small improvements regarding assertions, with the following example on master:
```
name: Assertions testsuite
testcases:
- name: ShouldBeLessThan
steps:
- script: echo '{"zero":0, "two":2, "five":5}'
assertions:
- 0 ShouldBeLessThan 5
- result.systemoutjson.zero ShouldBeLessThan "1"
- result.systemoutjson.zero ShouldBeLessThan result.systemoutjson.two
```
This assertion would panic because we are only checking inside the `dump` var.
solution: if cannot be found in `dump` var we can just use the actual value. (changes L89)
This assertion would fail because as opposed to above we don't check in the `dump` for the expected value, and we are trying to parse `result.systemoutjson.two`.
```
Testcase "test assertion", step #0: Assertion "result.systemoutjson.zero ShouldBeLessThan …
```
=> Small improvement to assertions

types.go
The following example causes a panic:
test.yaml
```yaml
name: Testy test
testcases:
- name: Testy test part 1
steps:
- type: test_part_1
```
lib/test_part_1.yaml
```yaml
executor: test_part_1
steps:
- type: http
method: PUT
url: http://localhost/v1/something/something/1234
```
backtrace:
```
venom run test.yaml
[trac] writing venom.log
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/ovh/venom.(*H).Add(...)
...go/pkg/mod/github.com/ovh/venom@v1.0.0-rc.4/types.go:27
github.com/ovh/venom.(*Venom).registerUserExecutors(0xc000356a20, 0x140fb40, 0xc0003cc7b0, 0xc00044e4e0, 0xb, 0xc0003cc480, 0xc0003cc4e0, 0xc0003cc7b0, 0x16)
...go/pkg/mod/github.com/ovh/venom@v1.0.0-rc.4/venom.go:228 +0x4c5
github.com/ovh/venom.(*Venom).GetExecutorRunner(0xc000356a20, 0x140fb40, …
```
=> Fix panic pointer and map are both nil

executors/redis/redis.go, tests/redis.yml
The Redis executor makes the assumption that if Redis returns an array as a response, this array will be flat, and there will be no arrays nested within it. This is not always the case (for example, **XREAD** and **XRANGE** return nested arrays).
This PR amends the Redis executor to parse Redis responses containing nested arrays, and includes a test-case to demonstrate how this functionality can be used with Redis steams.
Signed-off-by: chris1786 <22242927+chris1786@users.noreply.github.com>
=> Parse Redis responses containing nested arrays

process_files.go
close #405
from https://github.com/ovh/venom/blob/v0.28.0/templater.go#L115
=> fix: venom.datetime and venom.timestamp

cmd/venom/run/cmd.go, executors/amqp/README.md, executors/amqp/amqp.go, go.mod, go.sum, tests/Makefile, tests/amqp.yml
Add AMQP executor
This is primarily designed to support recent versions of QPID, but should also be compatible with ActiveMQ, and other brokers which implement the AMQP 1.0 specification.
Signed-off-by: chris1786 <22242927+chris1786@users.noreply.github.com>
=> Add AMQP executor

process_files.go, process_files_test.go
Signed-off-by: marc audefroy <marc.audefroy@corp.ovh.com>
Feature: Handle globstars ** for suite parameter.
Given this folder testsuites structure
```
MyApp/
testA/
test_a.yml 
testB/
test_b.yml 
testC/
test_c.yml 
```
If we ask MyApp/**/*.yml to venom. The getFilesPath method will returns
[testA/test_a.yml]
By using github.com/mattn/go-zglob, we can handle globstars. 
After modifications, getFilesPath method returns : 
[testA/testB/testC/test_c.yml testA/testB/test_b.yml testA/test_a.yml]
Before process_files modification, execute unit tests :
```
--- FAIL: Test_getFilesPath (0.00s)
--- FAIL: Test_getFilesPath/Check_globstars (0.00s)
process_files_test.go:22: Creating directory /var/folders/gd/g3_lfygs2r5_4x921ccgzmm80000gn/T/BTV27
process_files_test.go:113: Creating directory …
```
=> add globstars ** support

executors/kafka/kafka.go
Hello 👋 ,
I think I found one potential issue and one improvement for the Kafka executor:
I checked with a topic that has multiple partitions, and Sarama starts multiple goroutines in which the `handler` is used, so `ConsumeClaim` is called from and running in multiple goroutines concurrently. With that:
1. It can happen that despite a `messageLimit` of 1, after one goroutine added a message to `h.messages` and unlocks the mutex, another goroutine could enter and add another message.
- => Checking the message length _before_ adding another one should fix this
2. Let's say we use a key for filtering, and one goroutine found a matching msg and hits the `messageLimit` and returns. But other goroutines still continue running, because with the `continue` in the key filter condition it never …
=> Improve Kafka executor

process_testcase.go, tests/lib_custom/foobar_custom_multisteps.yml, tests/user_executor_custom_multisteps.yml
Closes #451
```
@lowlighter ➜ /workspaces/venom (feat-multistep) $ go run cmd/venom/main.go run tests/user_executor_custom_multisteps.yml --lib-dir tests/lib_custom/
• testsuite with a user executor in custom dir which has multiple steps (tests/user_executor_custom_multisteps.yml)
• testfoobar-multisteps-custom SUCCESS
```
=> feat(executors): expose previous steps result

README.md, process_testcase.go, tests/ranged.yml, types.go
May close #263 and close #288
This add support for the `range` attribute that can be passed in a step context.
The following types along their contexted variables are supported:
- `[]interface{}`: an array of values
- `.index`/`.key`: current iteration index
- `.value`: current iteration item value
- `map[string]interface{}`: a map of values (each key will be iterated over)
- `.index`: current iteration index
- `.key`: current iteration item key
- `.value`: current iteration item value
- `int`: an integer to perform action `n` times
- `.index`/`.key`/`.value`: current iteration index
- `string`: a templated string which results in one of the above typing 
- It can be either inherited from vars file, or interpolated from a previous step result 
Within a range context, `.range` variable …
=> feat(tests): add `range` supports

README.md, assertion.go, executors/README.md, executors/dbfixtures/dbfixtures.go, executors/exec/exec.go, executors/grpc/grpc.go, executors/http/http.go, executors/imap/imap.go, executors/kafka/kafka.go, executors/mqtt/mqtt.go, executors/ovhapi/ovhapi.go, executors/plugins/README.md, executors/plugins/hello/hello.go, executors/plugins/odbc/odbc.go, executors/rabbitmq/rabbitmq.go, executors/readfile/readfile.go, executors/smtp/smtp.go, executors/sql/sql.go, executors/ssh/ssh.go, tests/assertions_operators.yml, types.go
Closes #312 
This add support for logical operators syntax.
Supported operators are `and`, `or` and `xor`.
Nested operators are also supported.
There's a `not` operator too but it was added mostly to test that operators work correctly in tests case. User should use the respective "Not" assertions functions as a best practice rather than use it, that's why I didn't really document this one.
```yml
- name: Assertions operators
steps:
- script: echo 1
assertions:
- or:
- result.systemoutjson ShouldEqual 1 
- result.systemoutjson ShouldEqual 2
- or:
- result.systemoutjson ShouldBeGreaterThanOrEqualTo 1
- result.systemoutjson ShouldBeLessThanOrEqualTo 1
- or:
- result.systemoutjson ShouldEqual 1
```
=> feat(assertions): add logical operators

assertions/helper.go, tests/assertions/ShouldBeLessThan.yml
=> fix: handle json number is assertions

.build/go.mk, .golangci.yml, go.mod, go.sum
I submitted the initial use of linting, so here is an update with some improvements that 90poe has implemented internally.
There are a lot of linting errors, if you agree to add `make lint` as part of CI, I could work on PR to fix those errors.
Let me know.
=> Improve linter configuration

README.md, assertion.go, process_testcase.go, process_testsuite.go, tests/failing/must_assertion.yml, tests/lib_custom/foobar_custom_must_assertion.yml, tests/user_executor_custom_must_assertion.yml, types.go
Closes #459
Add support to `Must` assertions
Example:
```yml
- steps:
- type: exec
script: exit 1
assertions:
- result.code MustEqual 0
```
=> feat: `Must` assertions support

.gitignore, executors/exec/exec.go, process_testcase.go, process_teststep.go, tests/assertions_only.yml, types_executor.go, venom.go
Signed-off-by: François SAMIN <francois.samin@gmail.com>
=> feat: run testcase with assertion only

process.go, types.go
don't squash the commit related to #472 
=> fix: compute stats ok/ok/skipped on json format

cmd/venom/run/cmd.go
fix: when output defaults to XML, the file should have the '.xml' extension (#465)
Signed-off-by: Clement Sciascia <clement.sciascia@ovhcloud.com>
I wasn't sure where to put the default value, feel free to suggest a better way or edit my commit.
The default 'xml' value is already defined in the function that instantiates a Venom struct, but gets overwritten by this 'format' variable after flags parsing
=> Ensure the output file has '.xml' extension

types.go, venom_output.go
and fix the IS_TTY option
closes #454
=> fix: don't write invalid characters in report files

README.md, assertion.go, process_testcase.go, process_teststep.go, tests/failing/retry_if.yml, tests/retry_if.yml, types.go, types_executor.go, venom.go
Closes #458
Add support for `retry_if` to perform retries only while certains conditions are met.
Preview:
=> feat: add retry_if support on steps

executors/kafka/kafka.go
Upgrade Kakfa client version to 2.6.0 as older versions do not work correctly with RedPanda, Kafka cluster alternative, written in GO.
We use RedPanda as an alternative to Confluent Kafka, due to fact it takes ~300Mb to download and run single fast GO service, compared to 2.5Gb of download and run 3 slow starting Java services, which are required to run Kafka.
=> Upgrade Kakfa client version to 2.6.0

process_files.go
For this PR I started from an observation:
By default, `venom` CLI take in account *.yml* extension.
If it found .yml file, no need to specify them in the `venom run` command line:
```
$ tree /Users/avache/tmp/venom/2 ; go run main.go run /Users/avache/tmp/venom/2
/Users/avache/tmp/venom/2
└── testsuite.yml
0 directories, 1 file
[trac] writing venom.log
• APIIntegrationTest (/Users/avache/tmp/venom/2/testsuite.yml)
• GET-http-testcase-with-5-seconds-timeout SUCCESS
```
But it does not support *.yaml* extension file:
```
$ tree /Users/avache/tmp/venom/1 ; go run main.go run /Users/avache/tmp/venom/1
/Users/avache/tmp/venom/1
└── testsuite.yaml
0 directories, 1 file
[trac] writing venom.log
no yml file selected
exit status 2
```
But:
* YAML recommend that we use .yaml extension …
=> Venom: Support for .yml & .yaml extensions

cmd/venom/run/cmd.go
Following the PR on adding default *.yaml* extension support, it is useful to add this support in the CLI help message too :).
=> feat: add *.yaml extension in venom run usage message

process_teststep.go
Noticed that line numbers appear to be duplicated. I believe it stems from these lines. If `linenumber > 0` then the line number statement will be added twice, at lines 85 and 92 of the previous commit. This moves the second conditional statement into the else-clause of the first conditional statement, so it's only added once.
Signed-off-by: Sean Lane <sean.lane@neighbor.com>
=> Fix line numbers being duplicated

executors/rabbitmq/README.md
This fix a small typo of a missing `f`
=> fix small typo

README.md, assertions/assertions.go, assertions/assertions_test.go, tests/assertions/ShouldTimeEqual.yml
ShoudlEqual assertion return error when we try to compare time in differents location. 
To resolve this issue, we add ShouldEqualTime assertion to check equality between two time.Time. 
```
// ShouldTimeEqual receives exactly 2 time.Time arguments and does a time equality check.
// The arguments have to respect the date format RFC3339, as 2006-01-02T15:04:00+07:00
//
// Example of testsuite file:
//
//  name: test ShouldTimeEqual
//  vars:
//    time_1: 2006-01-02T13:04:00Z
//    time_2: 2006-01-02T15:04:00+02:00
//  testcases:
//  - name: test assertion
//    steps:
//    - type: exec
//      script: "echo {{.time}}"
//      assertions:
//        - result.systemout ShouldTimeEqual "{{.time_1}}" 
```
=> Add ShouldTimeEqual assertion

executors/grpc/grpc.go
Fix absolute file path for gRPC TLS certs:
Now you can provide absolute path for TLS certs files
=> Fix absolute file path for gRPC TLS certs

executors/kafka/README.md, executors/kafka/kafka.go, executors/kafka/schema_registry.go, tests/kafka/values/message3.json, tests/kafkaAvro.yml
This way there is no need to provide the AVSC file upon every message by retrieving the latest version from the schema registry, if available.
Code is using a [no longer maintained library](https://github.com/lensesio/schema-registry), I'd suggest to move to https://github.com/riferrei/srclient which is actively maintained.
If you agree, I can open a new PR with that change :).
Thanks for this great project!
=> Add feature to produce messages using latest schema available version

README.md
=> docs(contrib): typo and review of README.md

executors/http/http.go
this is related to https://github.com/ovh/venom/pull/528
sometimes there is extra param after the content type, like below
```
Content-Type: application/vnd.api+json; charset=utf-8
```
=> handle param like charset

README.md, process_testcase.go, tests/exec.yml, types.go
today, if one of the json elements can't be found, none of the resolution works
```yaml
name: Exec testsuite
testcases:
- name: catjson
steps:
- script: cat exec/testa.json
info: "the value of result.systemoutjson is {{.result.systemoutjson}}"
assertions:
- result.systemoutjson.foo ShouldContainSubstring bar
vars:
foo:
from: result.systemoutjson.foo
bar:
from: result.systemoutjson.bar
default: "test"
- script: echo "{{.catjson.foo}}"
info: "the value of foo is {{.catjson.foo}} {{.catjson.bar}}"
```
this is the output
```sh
• Exec testsuite (tests/exec.yml)
• catjson FAILURE
[info] the value of result.systemoutjson is {"foo":"bar"} (tests/exec.yml:29)
[info] the value of foo is {{.catjson.foo}} {{.catjson.bar}} (tests/exec.yml:39)
```
This change allows a `default` value to be specified …
=> feat: add default value for var

venom.go
Hello 👋 ,
We're running Venom inside of a Docker container in some cases, while mounting the scenario and custom executor files from the host into the container. Depending on the OS and the Docker config, for example when on macOS and having the "new Virtualization framework" enabled, but "VirtioFS" disabled, file operations can be very slow in Docker. Now with Venom we noticed that custom executors are read dozens of times during scenario execution, adding up to a lot of time.
Here's a screenshot of an example problematic Docker configuration on macOS:
But even with both of those options disabled, or both enabled, the file I/O is not great. For example we have a scenario that takes 1m, and 10s of that is spent purely on reading custom executor files!
This PR fixes that.
It introduces an …
=> Cache executor files

README.md, assertion.go, process_testcase.go, process_teststep.go, process_testsuite.go, tests/failing/verbose_output.yml, tests/verbose_output.yml, types.go, types_executor.go, venom.go
Closes #485
This is a followup of #453 
This PR introduces a detailed output:
- each step is logged whether it succeeded or not 
- failures, trace and info are displayed on associated step with correct indentation
- `range` are expanded and display current key for easier loop tracking
- `Must` failed assertions display the number of skipped steps 
Also fix some issues:
- `range` step dump were overwritten because they had the same name
- failures in `range` exited the range loop rather than fallthrough (default behaviour of steps)
- `-v` and `` had actually the same verbosity level
Preview (`-v` output):
Preview (default output):
=> feat: detailed steps output

process_testcase.go
=> fix: handle executor setup errors

cmd/venom/Makefile, cmd/venom/run/cmd.go, tests/Makefile, tests/interpolate_once.yml, tests/vars.yml, tests/vars/vars.yml
=> fix: interpolate arg var only once

cmd/venom/.gitignore, dump.go, executors/amqp/amqp.go, executors/http/http.go, executors/imap/imap.go, executors/kafka/kafka.go, executors/mqtt/mqtt.go, executors/rabbitmq/rabbitmq.go, executors/readfile/readfile.go, executors/smtp/smtp.go, go.mod, go.sum, tests/interpolation.yml, tests/readfile.yml
It's now possible to read something like that :
```json
{
"foo": "bar",
"FOO": "truc",
}
```
and use these variables:
```yml
- type: readfile
path: the_file.json
info: "{{.Result.ContentJSON.foo}}-{{.Result.ContentJSON.FOO}}"
```
Environment variable: VENOM_PRESERVE_CASE
venom 1.1.x
VENOM_PRESERVE_CASE="AUTO" is equals to VENOM_PRESERVE_CASE="OFF"
venom 1.2.x
VENOM_PRESERVE_CASE="AUTO" is equals to VENOM_PRESERVE_CASE="ON"
venom 1.1 users, you can try:
```sh
> export VENOM_PRESERVE_CASE="ON";
> venom run ...
```
close #522
close #547
close #522
=> feat: preserve case

cmd/venom/main.go, cmd/venom/root/root.go, cmd/venom/run/cmd.go, executors/registry.go
This refactoring allows users to use venom as a library and easily create "venom-like" CLIs with their own custom executors which may not make sense in the main venom repository.
NOTE - this is purely a cosmetic refactoring. This should not affect how venom functions at all.
This is possible through something like - 
```go
package main
import (
log "github.com/sirupsen/logrus"
"github.com/ovh/venom/executors"
"github.com/ovh/venom/cmd/venom/root"
)
func main() {
addCustomExecutors()
if err := root.New().Execute(); err != nil {
log.Fatalf("Err:%s", err)
}
}
func addCustomExecutors() {
executors.Registry[myExecutor.Name] = myExecutor.New
}
```
=> Add a registry variable to source executors from

.gitignore, Makefile, README.md, assertion.go, cmd/cli.go, cmd/venom/.gitignore, cmd/venom/run/cmd.go, process.go, process_files.go, process_testcase.go, process_teststep.go, process_testsuite.go, tests/.gitignore, tests/Makefile, tests/retry_if.yml, tests/user_executor_custom_must_assertion.yml, tests/verbose_output.yml, types.go, types_executor.go, venom.go, venom_output.go, venom_output.html, venom_output_html.go
example of usage:
venom run --format=html --output-dir=. *.yml
venom run --format=html,json --output-dir=. *.yml
refact internal struct, json output is more detailed
close #20
=> feat: output html

process_teststep.go, venom_output.go
=> fix(executor/exec): manage \n in xml output

README.md, cmd/venom/run/cmd.go, process_files.go, tests/Makefile, types.go, venom.go, venom_output.go
generate unique file per testsuite
format can have only one value
fix line number in failure data
close #577
=> refactor: --html-report instead of format=html

process_testcase.go, process_testsuite.go, tests/verbose_output.yml, types.go
=> feat: improve output with range

README.md, process_testcase.go, process_testsuite.go, tests/skip.yml, types.go
Closes #486 
Make it possible to `skip` at step level (currently it's only possible to do so at case level)
If all steps from a case are skipped, then the case will also change its state to "SKIP" rather than "PASS"
*Default output:*
*Verbose output:*
Additionally this slightly changes the output of skipped test case when verbose mode is enabled to display that "all steps were skipped" rather than nothing, which could be misleading as a user may think that something is wrong with their test case definition
<details>
<summary>Current output</summary>
</details>
=> feat: `skip` support at step level

README.md, assertion.go, assertions/assertions.go, cmd/venom/run/cmd.go, executors/README.md, executors/exec/exec.go, executors/http/README.md, executors/kafka/README.md, executors/kafka/kafka.go, executors/plugins/odbc/README.md, executors/rabbitmq/README.md, executors/rabbitmq/rabbitmq.go, executors/readfile/readfile.go, executors/redis/README.md, executors/sql/README.md, executors/web/types.go, process_testcase.go, process_testcase_test.go, process_testsuite.go, tests/Makefile, tests/grpc/mock.js, tests/rabbitMQ.yml, tests/ranged.yml, types.go, types_executor.go, types_test.go, variable_helpers.md, venom.go
=> fix: typos

README.md, executors/dbfixtures/README.md, executors/dbfixtures/dbfixtures.go, tests/db_fixtures.yml, tests/dbfixtures/testdata/schemas/sqlite3.sql
It seems the underlying libraries used by `dbfixtures` support sqlite3, so I'm adding support for it as well.
I **think** the tests are passing locally, that's why I'm opening this PR, but TBH I'm not completely sure: `make integration-test` exits successfully with `0`, but I don't see any venom output in my stdout.
Do let me know if anything else needs changing.
=> Add support for sqlite3 to dbfixtures executor

dump.go, tests/case.yml, tests/interpolation.yml
It's now possible to read something like that :
```json
{
"foo": "bar",
"FOO": "truc",
}
```
and use these variables:
```yml
- type: readfile
path: the_file.json
info: "{{.Result.ContentJSON.foo}}-{{.Result.ContentJSON.FOO}}"
```
Environment variable: VENOM_PRESERVE_CASE
venom 1.1.x
VENOM_PRESERVE_CASE="AUTO" is equals to VENOM_PRESERVE_CASE="OFF"
venom 1.2.x
VENOM_PRESERVE_CASE="AUTO" is equals to VENOM_PRESERVE_CASE="ON"
venom 1.1 users, you can try:
```sh
> export VENOM_PRESERVE_CASE="ON";
> venom run ...
```
=> feat: VENOM_PRESERVE_CASE default ON

executors/exec/exec.go
When trying to do **crimes** to get around  #604 I found a way to crash the exec executor.
This fixes said crash. 
Sadly I don't have the code that caused the error anymore so I can't provide it here.
=> fix(exec): panic on cmd.Start error

assertions/assertions.go, assertions/assertions_test.go
It is possible to trigger `nil` pointer dereference by calling `ShouldContain` assertions.
Possible minimal reproducer in `venom`:
```yaml
testcases:
- steps:
- assertions:
- result.systemoutjson ShouldContain value
```
This PR fixes that by avoiding unconditional calls to `Kind()` when `ShouldContain()` contains a `nil` pointer like in previous example and adds a test to double-check that.
=> fix: avoid `nil` pointer dereference in `ShouldContain` assertions

venom_output.go
Value is converted from float64 to string. This will resolve gh actions test reporters for junit xml, showing missing test suite time execution values
=> fix: TestSuiteXML is missing the Time property

process_testcase.go, process_teststep.go, process_testsuite.go, types.go, types_executor.go
- removed ranged prints on non-verbose runs
- fixed info not interpolating right variable in step X with .result variable (was showing variable from X-1)
- print info before errors: closes #597 
- on non-verbose runs, print info only when there're failures: closes #595
=> feat: removed result from testcase variables and removed errors warning and info from non verbose runs

executors/http/http.go, tests/case.yml
Signed-off-by: François Samin <francois.samin@corp.ovh.com>
=> fix(http): preserve BodyFile absolute path

executors/mongo/README.md, executors/mongo/mongo.go, go.mod, tests/mongo.yml, tests/mongo/fixturesA/cards.yml, tests/mongo/fixturesB/pokemons.yml
It works roughly the same as the dbfixtures executor. I wanted to implement it directly in dbfixtures but it's too tied to database/sql so it doesn't work well with Mongo
Note that I used yaml.v3 instead of v2, because v2 unmarshals yaml objects as `map[any]any` instead of `map[string]any`, it's too hard to deal with when inserting in Mongo
=> feat(mongo): add "loadFixtures" action

executors/http/README.md, executors/http/http.go, tests/http.yml
This allows specifying the query parameters and properly encode them.
This is for issue #625
=> feat: allow specifying query parameters

README.md, assertions/assertions.go, assertions/assertions_test.go, tests/assertions/ShouldMatchRegex.yml, tests/failing/assertions_regex.yml
#643 working on having that ability
=> working on ShouldMatchRegex

README.md
Fix common user example gave in the README.
=> fix: Remove trailing slash on README example

cmd/venom/run/cmd.go, executors/exec/exec.go, log.go, log_test.go, process.go, process_files.go, process_testcase.go, process_teststep.go, process_testsuite.go, tests/hide_secrets.yml, types.go, venom.go, venom_output.go
Adding secrets in the context and creating a function that we can call to hide sensitive data
Add the ability to mark variables as secrets in the testsuite so that the venom.log does not show them
#476
=> Adding secrets field and refactoring the logging process. 

assertions/assertions.go, assertions/assertions_test.go, go.mod, go.sum, tests/assertions/ShouldHappenAfter.yml, tests/assertions/ShouldHappenBefore.yml, tests/assertions/ShouldHappenBetween.yml, tests/assertions/ShouldHappenOnOrAfter.yml, tests/assertions/ShouldHappenOnOrBefore.yml
This PR will add ability to easily assert date time. 
Now we can use time assertion in natural language.
Example:
```yaml
name: test ShouldHappenBetween
testcases:
- name: test assertion with humanize format
steps:
- type: exec
script: "echo {{.venom.datetime}}"
assertions:
- "result.systemout ShouldHappenBetween yesterday tomorrow"
- "result.systemout ShouldHappenBetween '5 minutes ago' '5 minutes from now'"
```
This PR uses https://github.com/tj/go-naturaldate to support the natural language.
=> add natural language datetime assertion

cmd/venom/run/cmd.go, cmd/venom/run/cmd_test.go
This PR fixes the following issue:
VENOM_VAR_a='host=localhost'
results in a='host' because of the split on '=' and only taking the first value back
With this the var would end up like this:
a = 'host=localhost'
Making it possible to add equal signs in the variable
=> fix(venom): env variables with equal sign

process_teststep.go, process_testsuite.go, types.go, types_executor.go
```yml
name: testsuite with a user executor
testcases:
- name: testJSON
steps:
- type: hello
myarg: World
- type: hello
myarg: World
- name: testJSON
steps:
- type: hello
myarg: World
```
returns:
```
❯ venom run -vvv b.yml
[trac] writing venom.2.log
• testsuite with a user executor (b.yml)
• testJSON
• hello PASS
• hello PASS
[trac] writing b.testJSON.testcase.0.step.0.0.dump.json
[trac] writing b.testJSON.testcase.0.step.1.0.dump.json
• testJSON
• hello PASS
[trac] writing b.testJSON.testcase.1.step.0.0.dump.json
final status: PASS
```
close #722
=> fix(venom): output dump file

executors/sql/README.md
This PR amends examples for query length in the documentation to match beta4 changes.
=> Update examples for queries length assert #763

executors/exec/README.md, executors/exec/exec.go, tests/exec.yml
If set, the value is written to the script stdin. This avoid the need to use 'echo' in the script, which makes thing clearer.
It is also particularly useful in the following case (probably other issues with variable substitution):
```yaml
name: simple_test
vars:
payload: {"s": "\n"}
testcases:
- name: simple_test
steps:
- type: exec
script: echo {{.payload | toJSON}} | jq .
assertions:
- result.code MustEqual 0
```
This will fail because the \n is not properly escaped.
Using the new stdin attribute solves the issue:
```yaml
name: simple_test
vars:
payload: {"s": "\n"}
testcases:
- name: simple_test
steps:
- type: exec
stdin: {{.payload | toJSON}}
script: jq .
assertions:
- result.code MustEqual 0
```
=> exec: add a 'stdin' attribute

README.md, process_files.go, types.go, venom_output.html
This attribute expects a markdown content.
If defined, the html output will render it in the 'info' header of the test stuite.
=> suite: add a 'description' property

executors/redis/redis.go, go.mod, go.sum
Hello,
Bump the redis client to the latest version to support ACL (introduced [here](https://github.com/gomodule/redigo/pull/480))
Btw, the `garyburd/redigo/redis` has moved to `gomodule/redigo/redis`. The old repo is unmaintained.
```yml
- name: Test commands
steps:
- type: redis
dialURL: "redis://{{.user}}:{{.password}}@localhost:6379/0"
commands:
- SET foo bar
- GET foo
- KEYS *
assertions:
- result.commands.commands0.response ShouldEqual OK
- result.commands.commands1.response ShouldEqual bar
- result.commands.commands2.response.response0 ShouldEqual foo
```
```bash
• Test-commands
• redis FAIL
Testcase "Test commands", step #0-0: WRONGPASS invalid username-password pair or user is disabled.
final status: FAIL
```
```bash
• Test-commands
• redis PASS
final status: PASS
```
=> feat(executor/redis): Redis auth (ACL) support

.build/go.mk
When fetching Venom binaries, I noticed that Windows releases didn't include an extension. For Windows, it means that the users will face the program-picker prompt due to a lack of extension, and would have to add it manually. 
This PR changes the `CROSS_COMPILED_BINARIES` make target in `.build/go.mk` to check if the current target OS is windows, and if so, changing the filename to include the `.exe` extension.
I assume that the point of `BINARIES` is precisely this, but probably due to some lack of Make syntax knowledge, I couldn't figure out why `IS_WINDOWS` isn't being recognized :) 
That being the case, I am opening a suggestion to leverage the `GOOS` env var taken from the `get_os_from_binary_file` call, and changing the filename if the OS is `windows`.
Any suggestions for changes …
=> fix: [Make] Create windows binaries with .exe extension

executors/rabbitmq/README.md, executors/rabbitmq/rabbitmq.go
Introduced new client type to use for testing RPC pattern using [Direct Reply-to](https://www.rabbitmq.com/docs/direct-reply-to).
This can not be achieved using existing client types (publisher and subscriber), because a Direct reply-to has some specific requirements and the client must have a reply consumer running before publishing a request.
The new client type is simply referred to as 'client' to indicate a client-server communication using RPC pattern.
It can be used to test a server that is expected to respond to the received message by sending a reply using Direct Reply-to feature of RabbitMQ.
Example testsuite:
```
name: TestSuite RabbitMQ
testcases:
- name: Send data and await reply
steps:
- type: rabbitmq
addrs: "{{.addrs}}"
user: "{{.user}}"
password: "{{.password}}" …
```
=> feat(executor/rabbitmq): Add support for RPC

README.md, process_testcase.go, process_testsuite.go
close https://github.com/ovh/venom/issues/808
```json
"venom.testcase.totalSteps": "3",
"venom.teststep.number": "1",
"venom.testsuite.totalSteps": "5",
```
- I have adjusted the `teststep.number` and test case numbering to be 1-based instead of zero-based indexing.
Now, the dumps logged in the console will display as follows:
```bash
• test.venom (test.venom.yml)
• Test-1
• http PASS
• http PASS
[trac] writing output/test-venom.Test-1.testcase.1.step.1.0.dump.json
[trac] writing output/test-venom.Test-1.testcase.1.step.2.0.dump.json
• Test-2
• http PASS
• http PASS
• http PASS
[trac] writing output/test-venom.Test-2.testcase.2.step.1.0.dump.json
[trac] writing output/test-venom.Test-2.testcase.2.step.2.0.dump.json
[trac] writing output/test-venom.Test-2.testcase.2.step.3.0.dump.json
```
=> feat: test case and test suite `totalSteps` built-in variables added

Dockerfile
=> fix: Copy venom binary to standard practice location

process_testcase.go, tests/skip.yml
Hi,
it should close #777 
```yaml
name: "Do not skip testcase"
vars:
set_var_exit_code: 2
testcases:
- name: skip-test-step-same-test-case
steps:
- name: init
type: exec
script: exit 0
assertions:
- result.code ShouldEqual 0
vars:
set_var_exit_code:
from: result.code
- name: dont-skip-step
type: exec
script: echo set_var_exit_code={{.skip-test-step-same-test-case.exit_step_code}}
skip:
- skip-test-step-same-test-case.set_var_exit_code ShouldEqual 0
- name: skip-step
type: exec
script: echo set_var_exit_code={{.skip-test-step-same-test-case.exit_step_code}}
skip:
- skip-test-step-same-test-case.set_var_exit_code ShouldNotBeNil
- skip-test-step-same-test-case.set_var_exit_code ShouldEqual 1
- name: dont-skip-step
type: exec
script: echo …
```
=> fix(teststep): include step previous vars when checking skip

process_testcase.go
Fixes an issue where `info` from user executors (and sub executors) aren't logged since v1.2.0-beta and logging refactor.
Proposals:
1. Move back up logs from user executors to parent teststep and let the teststep itself log the infos (current implementation)
2. Edit condition with `v.Verbose >=1` to make the user executor log its own logs, it will however needs checking to avoid relogging test step result (PASS, FAIL, SKIP).
Feel free to ask for whichever fix, I will take care of the implementation.
Tested with:
```sh
go build ./cmd/venom
./venom run --lib-dir=tests/lib ./tests/user_executor_many.yml -v
[trac] writing venom.30.log
• Many user executor (./tests/user_executor_many.yml)
• info
• exec PASS
[info] value foo vars foo_from_vars
• mytc
• userExecutorA PASS
[info] value on A: …
```
=> fix(testcase): log correctly user executors info - fixes #699

process_teststep.go, process_testsuite.go, venom_output.go
Fixes an issue for Windows where report files can't be written since we were replacing / by _ and not taking into account Windows separator \.
Proposals:
1. Only use testfile name and not the whole path for the test result filename (current implementation).
2. Extend replace to os.PathSeparator which will replace \ or / depending on executing OS.
=> fix(reports): use filepath.Join instead or linux sep or path.Join for file that will be written on OS - fixes #794

executors/http/README.md, executors/http/http.go, executors/http/http_test.go
This PR aims at supporting cookies in same-step redirects.
It does not handle cookies more globally (across steps).
=> feat(http): support cookies in redirects
